PREFLAGS =

PREFLAGS += -DNULL_CHECK
PREFLAGS += -DBOUNDS_CHECK
PREFLAGS += -DRANGE_CHECK
PREFLAGS += -DDEVICE_CHECK
PREFLAGS += -DASSERT_BUILD
PREFLAGS += -DRETURN_CODES
PREFLAGS += -DKERNEL_PERF
#PREFLAGS += -DKERNEL_PERF_VERBOSE
